// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotSteam.Infrastructure.Data;

namespace NotSteam.Infrastructure.Migrations
{
    [DbContext(typeof(NotSteamContext))]
    [Migration("20190825152551_Initial1")]
    partial class Initial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("NotSteam.Model.Models.AuthUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Nickname")
                        .HasMaxLength(32);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("ProfileImageUri");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            DateOfBirth = new DateTime(1996, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Player123@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "xXSlayerXx",
                            PhoneNumberConfirmed = false,
                            ProfileImageUri = "https://cdn.notsteam.com/images/1",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            DateOfBirth = new DateTime(1992, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "NobodyReally@outlook.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "Sgt. Harry",
                            PhoneNumberConfirmed = false,
                            ProfileImageUri = "https://cdn.notsteam.com/images/2",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            DateOfBirth = new DateTime(1989, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "SampleText@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "Mr.Boom",
                            PhoneNumberConfirmed = false,
                            ProfileImageUri = "https://cdn.notsteam.com/images/3",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("NotSteam.Model.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(1500);

                    b.Property<string>("HomepageUri");

                    b.Property<string>("LogoImageUri");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 567, DateTimeKind.Utc).AddTicks(2409),
                            Description = "We make really cool games!",
                            HomepageUri = "https://www.methesda-softworks.com",
                            LogoImageUri = "https://cdn.notsteam.com/images/101",
                            Name = "Methesda Softworks Inc."
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 567, DateTimeKind.Utc).AddTicks(3709),
                            Description = "We make tech demos!",
                            HomepageUri = "https://www.crymearivertek.com",
                            LogoImageUri = "https://cdn.notsteam.com/images/102",
                            Name = "CryMeARiverTek GmbH"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 567, DateTimeKind.Utc).AddTicks(3721),
                            Description = "We make great action-adventure, role-playing games!",
                            HomepageUri = "https://www.dvd-projekt-blue.com",
                            LogoImageUri = "https://cdn.notsteam.com/images/103",
                            Name = "DVD Projekt Blue"
                        });
                });

            modelBuilder.Entity("NotSteam.Model.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("CompanyId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(1500);

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 59.99m,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 568, DateTimeKind.Utc).AddTicks(4432),
                            Description = "New year, new game!",
                            ReleaseDate = new DateTime(2019, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "C4ll of $$$$: Covert Ops"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 79.99m,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 568, DateTimeKind.Utc).AddTicks(6184),
                            Description = "What we really want from EA.",
                            ReleaseDate = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Need for Speed: Underground 3"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 69.69m,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 568, DateTimeKind.Utc).AddTicks(6197),
                            Description = "One of these days…",
                            ReleaseDate = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Age of Empires 4"
                        });
                });

            modelBuilder.Entity("NotSteam.Model.Models.GameTag", b =>
                {
                    b.Property<int>("GameId");

                    b.Property<int>("TagId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("GameId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("GameTags");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            TagId = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 569, DateTimeKind.Utc).AddTicks(320)
                        },
                        new
                        {
                            GameId = 1,
                            TagId = 2,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 569, DateTimeKind.Utc).AddTicks(1375)
                        },
                        new
                        {
                            GameId = 2,
                            TagId = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 569, DateTimeKind.Utc).AddTicks(1387)
                        },
                        new
                        {
                            GameId = 2,
                            TagId = 2,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 569, DateTimeKind.Utc).AddTicks(1388)
                        },
                        new
                        {
                            GameId = 2,
                            TagId = 3,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 569, DateTimeKind.Utc).AddTicks(1389)
                        },
                        new
                        {
                            GameId = 3,
                            TagId = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 569, DateTimeKind.Utc).AddTicks(1390)
                        });
                });

            modelBuilder.Entity("NotSteam.Model.Models.Library", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("GameId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("DateAcquired");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<DateTime?>("LastPlayedDate");

                    b.Property<int>("TotalPlayTimeHours");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("Libraries");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            GameId = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 569, DateTimeKind.Utc).AddTicks(6389),
                            DateAcquired = new DateTime(2019, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastPlayedDate = new DateTime(2019, 8, 25, 15, 25, 51, 569, DateTimeKind.Utc).AddTicks(6389),
                            TotalPlayTimeHours = 20
                        },
                        new
                        {
                            UserId = 1,
                            GameId = 2,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 569, DateTimeKind.Utc).AddTicks(7622),
                            DateAcquired = new DateTime(2019, 8, 25, 15, 25, 51, 569, DateTimeKind.Utc).AddTicks(7621),
                            LastPlayedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPlayTimeHours = 0
                        },
                        new
                        {
                            UserId = 2,
                            GameId = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 569, DateTimeKind.Utc).AddTicks(7691),
                            DateAcquired = new DateTime(2019, 7, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastPlayedDate = new DateTime(2019, 8, 25, 15, 25, 51, 569, DateTimeKind.Utc).AddTicks(7691),
                            TotalPlayTimeHours = 903
                        });
                });

            modelBuilder.Entity("NotSteam.Model.Models.Purchase", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("GameId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("DateOfPurchase");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            GameId = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 570, DateTimeKind.Utc).AddTicks(2590),
                            DateOfPurchase = new DateTime(2019, 7, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalPrice = 59.99m
                        },
                        new
                        {
                            UserId = 1,
                            GameId = 2,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 570, DateTimeKind.Utc).AddTicks(4090),
                            DateOfPurchase = new DateTime(2019, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalPrice = 64.99m
                        },
                        new
                        {
                            UserId = 2,
                            GameId = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 570, DateTimeKind.Utc).AddTicks(4104),
                            DateOfPurchase = new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalPrice = 24.99m
                        });
                });

            modelBuilder.Entity("NotSteam.Model.Models.Review", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("GameId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(1500);

                    b.Property<int>("Rating");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            GameId = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 570, DateTimeKind.Utc).AddTicks(7562),
                            Description = "This is a really good game! You should get it too!",
                            Rating = 8
                        },
                        new
                        {
                            UserId = 2,
                            GameId = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 570, DateTimeKind.Utc).AddTicks(8810),
                            Description = "It's a good game, but I don't like \"surprise mechanics\".",
                            Rating = 6
                        });
                });

            modelBuilder.Entity("NotSteam.Model.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(48);

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 567, DateTimeKind.Utc).AddTicks(7328),
                            Description = "This item contains single-player content (e.g. campaign, story mode, etc.)",
                            Name = "Single-Player"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 567, DateTimeKind.Utc).AddTicks(8483),
                            Description = "This item contains multi-player content. Requires an internet connection.",
                            Name = "Multi-Player"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 8, 25, 15, 25, 51, 567, DateTimeKind.Utc).AddTicks(8494),
                            Description = "This item contains ce-op content. Requires an internet connection. A limited amount of players can group up and play!",
                            Name = "Co-Op"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("NotSteam.Model.Models.AuthUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("NotSteam.Model.Models.AuthUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NotSteam.Model.Models.AuthUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("NotSteam.Model.Models.AuthUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NotSteam.Model.Models.Game", b =>
                {
                    b.HasOne("NotSteam.Model.Models.Company", "Company")
                        .WithMany("Games")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NotSteam.Model.Models.GameTag", b =>
                {
                    b.HasOne("NotSteam.Model.Models.Game", "Game")
                        .WithMany("GameTags")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NotSteam.Model.Models.Tag", "Tag")
                        .WithMany("GameTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NotSteam.Model.Models.Library", b =>
                {
                    b.HasOne("NotSteam.Model.Models.Game", "Game")
                        .WithMany("Libraries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NotSteam.Model.Models.AuthUser", "User")
                        .WithMany("Libraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NotSteam.Model.Models.Purchase", b =>
                {
                    b.HasOne("NotSteam.Model.Models.Game", "Game")
                        .WithMany("Purchases")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NotSteam.Model.Models.AuthUser", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NotSteam.Model.Models.Review", b =>
                {
                    b.HasOne("NotSteam.Model.Models.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NotSteam.Model.Models.AuthUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
